### ISSUE TITLE
option-click should open resulting view in new tab on: https://game.learnersguild.org/projects/

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#921] opened 2017-07-07 23:31 UTC
All the clickable elements on https://game.learnersguild.org/projects/ are not links. This means you cannot (for example) cmd-click on them to open in a new tab or right-click to do many link related actions. Please don't use onClick and instead use a real link. 

:)

**Comment by jeffreywescott** [comment] 2017-07-07 23:31
**[Comment from Clubhouse user @prattsj:]** **[Comment from GitHub user @prattsj:]** Will take a look at it, but we're using the default table component out of the box from [react-toolbox](http://react-toolbox.com/#/components/table). Sad to say that's the way it was implemented. Been considering creating/using a different table component for various reasons (this isn't the only thing I find problematic about it 😐).

**Comment by jeffreywescott** [comment] 2017-07-07 23:31
**[Comment from Clubhouse user @prattsj:]** **[Comment from GitHub user @prattsj:]** Also @deadlyicon: probably safer to put these kinds of requests in the los repo (https://github.com/LearnersGuild/los/issues). 🙂

**Comment by jeffreywescott** [comment] 2017-07-07 23:31
**[Comment from Clubhouse user @prattsj:]** **[Comment from GitHub user @prattsj:]** Also, it's technically not a bug - working as designed. :/

**Comment by jeffreywescott** [comment] 2017-07-07 23:31
**[Comment from Clubhouse user @prattsj:]** **[Comment from GitHub user @deadlyicon:]** @prattsj thanks I'll make all new requests there. Thank you! :)

**Comment by jeffreywescott** [comment] 2017-07-07 23:31
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment] 2017-07-14 03:24
Duplicate of https://github.com/LearnersGuild/echo/issues/707.

**Closed by prattsj** 2017-07-14 03:24 UTC
Labels: enhancement, ui
