### ISSUE TITLE
change UserForm phase input control to dropdown

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#944] opened 2017-07-10 18:02 UTC
From [ch3333](https://app.clubhouse.io/learnersguild/story/3333)

currently a text input.

**Comment by jeffreywescott** [comment] 2017-07-10 18:02
**[Comment from Clubhouse user @prattsj:]** Moved to github issue for work in P4:
https://github.com/LearnersGuild/echo/issues/910

**Comment by jeffreywescott** [comment] 2017-07-10 18:02
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: should we archive this?

**Comment by prattsj** [comment] 2017-07-10 18:06
Duplicate of #910.

**Closed by prattsj** 2017-07-10 18:06 UTC
