### ISSUE TITLE
chapter names should enforce case-insensitive uniqueness

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#991] opened 2017-07-10 19:11 UTC
From [ch354](https://app.clubhouse.io/learnersguild/story/354)

Possible to have two separate chapters named "Todton" and "todton".

**Comment by jeffreywescott** [comment] 2017-07-10 19:11
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: move to P4 GH?

**Comment by prattsj** [comment] 2017-07-14 03:15
Duplicate of https://github.com/LearnersGuild/echo/issues/987.

**Closed by prattsj** 2017-07-14 03:15 UTC
Labels: database, ui
