### ISSUE TITLE
user avatars not showing in cycle voting results

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/echo#941] opened 2017-07-10 18:02 UTC
From [ch3660](https://app.clubhouse.io/learnersguild/story/3660)

![Screen Shot 2017-07-05 at 12.40.29 PM.png](https://clubhouse-assets.s3.amazonaws.com/586b24df-3b14-4cb6-b4b4-e78b31bf192e/595d1f31-ef15-405a-95ff-c8e459b1bd03/Screen%20Shot%202017-07-05%20at%2012.40.29%20PM.png)

**Comment by jeffreywescott** [comment] 2017-07-10 18:02
**[Comment from Clubhouse user @prattsj:]** Moved to github issue for work by P4 members:
https://github.com/LearnersGuild/echo/issues/907

**Comment by jeffreywescott** [comment] 2017-07-10 18:02
**[Comment from Clubhouse user @jeffreywescott:]** @prattsj: should we archive this?

**Comment by prattsj** [comment] 2017-07-10 18:07
Duplicate of #907.

**Closed by prattsj** 2017-07-10 18:07 UTC
